# Generated by Django 5.0.1 on 2024-01-27 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlists_as_id_user', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlists_as_list_user', to=settings.AUTH_USER_MODEL, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Список користувачів',
                'verbose_name_plural': 'Список користувачів',
            },
        ),
    ]
