# Generated by Django 5.0.1 on 2024-01-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0002_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(max_length=8, verbose_name='Ключ'),
        ),
    ]
