# Generated by Django 5.0.1 on 2024-01-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0003_alter_userprofile_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=16, verbose_name='Ключ')),
                ('user_1', models.TextField(blank=True, verbose_name='Користувач 1')),
                ('user_2', models.TextField(blank=True, verbose_name='Користувач 2')),
                ('messeg_1', models.TextField(blank=True, verbose_name='Повідомленя 1')),
                ('messeg_2', models.TextField(blank=True, verbose_name='Повідомленя 2')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
    ]
