# Generated by Django 5.0.1 on 2024-02-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0005_messeg_messeg_3_alter_messeg_messeg_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='GroupMesseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messeg_1', models.TextField(blank=True, verbose_name='Повідомленя 1')),
                ('messeg_2', models.TextField(blank=True, verbose_name='Посилання Зображеня')),
                ('messeg_3', models.TextField(blank=True, verbose_name='Посилання')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Natiskun.group', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
    ]
