# Generated by Django 5.0.1 on 2024-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0006_group_groupmesseg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmesseg',
            options={'verbose_name': 'Повідомлення групи', 'verbose_name_plural': 'Повідомлення групи'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(to='Natiskun.group', verbose_name='Групи користувача'),
        ),
    ]
