# Generated by Django 5.0.1 on 2024-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0007_alter_groupmesseg_options_userprofile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fon',
            field=models.ImageField(default='group/fon1.jpg', upload_to='group'),
        ),
    ]
