# Generated by Django 5.0.1 on 2024-02-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natiskun', '0008_group_fon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmesseg',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Natiskun.group', verbose_name='Група'),
        ),
        migrations.CreateModel(
            name='CommentsGroupMesseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messeg_1', models.TextField(blank=True, verbose_name='Повідомленя 1')),
                ('messeg_2', models.TextField(blank=True, verbose_name='Посилання Зображеня')),
                ('messeg_3', models.TextField(blank=True, verbose_name='Посилання')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Natiskun.groupmesseg', verbose_name='Пост')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Коментарі',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
